version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: system tasks REST
    restart: always
    command: --ISCAgent false
    ports:
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
